### PR TITLE
Fix/auth log

### PR DESCRIPTION
**Pull request by pranavrd**

### CODE REVIEW

**Comment by kailash** [comment]
ok to test

**Comment by kailash** [comment]
add to whitelist

**Comment by karun-singh** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Comment by kailash** [comment]
restart this please

**Comment by kailash** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Comment by pranavrd** [comment]
retest this please

**Comment by pranavrd** [comment]
retest this please

**Pull request merged**
