### PR TITLE
NLP search enhanced

### PR DESCRIPTION
**Pull request by pranavrd**

### CODE REVIEW

**Comment by pranavrd** [comment]
retest this please

**Comment by pranavrd** [comment]
retest this please

**Comment by pranavrd** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Review by gopal-mahajan — APPROVED** [review]
LGTM

**Review by kailash — APPROVED** [review]
LGTM

**Pull request merged**
