### PR TITLE
domain and provider API

### PR DESCRIPTION
**Pull request by tanvi029**

### CODE REVIEW

**Comment by kailash** [comment]
ok to test

**Review by pranavrd — APPROVED** [review]
LGTM

**Comment by kailash** [comment]
retest this please

**Comment by pranavrd** [comment]
retest this please

**Comment by kailash** [comment]
retest this please

**Comment by kailash** [comment]
retest this please

**Comment by kailash** [comment]
retest this please

**Comment by pranavrd** [comment]
retest this please

**Pull request merged**
